tuling:
  url: http://www.tuling123.com/openapi/api
  keys: {
    "采姑娘的大蘑菇": {name: "Robert", key: "626621c5dfd9a388a9048689e5f162e0"},
  }

log:
  formatter: "logstash"
  level: info
  writer:
    type: file
    path: wecat.log